name: Publish Mod

# Run when a new release is... released
on: 
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Thunderstore
    steps:
      # Use checkout to publish the files in your repo
      - uses: actions/checkout@v3
      - uses: GreenTF/upload-thunderstore-package@v3.1
        with:    
          environment: Thunderstore
          namespace: EladNLG # the thunderstore 'team' to publish under
          description: Do you like bugs? So do I.
          token: ${{ secrets.THUNDERSTORE_TOKEN }}
          name: RoguelikeBeta # the name of the package
          version: ${{ github.ref_name }} # Use the tag as the package version
          community: Northstar
